In [2]:
import numpy as np

In [3]:
array1=np.array([1,2,3,4,5]) #1D array

In [4]:
array2=np.array([   #2D array
    [1,2,3,4,5],
    [6,7,8,9,11]]
)

In [5]:
print(array1)

[1 2 3 4 5]


In [6]:
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 11]]


In [7]:
array3=np.array([[  #3D array
    [1,2,3,4,5],
    [6,7,8,9,0],
    [11,22,33,44,55]
],
                [
                    [12,14,13,16,17],
                    [21,22,23,24,33],
                    [31,32,33,34,35]
                ]])

In [8]:
print(array3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9  0]
  [11 22 33 44 55]]

 [[12 14 13 16 17]
  [21 22 23 24 33]
  [31 32 33 34 35]]]


In [9]:
array4=np.ones((2,5,4)) # 2 matrix , 5 column and 4 rows

In [10]:
print(array4)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [11]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
array6=np.linspace(1,10,76)  #1 to 10 but 76 steps

In [13]:
print(array6)

[ 1.    1.12  1.24  1.36  1.48  1.6   1.72  1.84  1.96  2.08  2.2   2.32
  2.44  2.56  2.68  2.8   2.92  3.04  3.16  3.28  3.4   3.52  3.64  3.76
  3.88  4.    4.12  4.24  4.36  4.48  4.6   4.72  4.84  4.96  5.08  5.2
  5.32  5.44  5.56  5.68  5.8   5.92  6.04  6.16  6.28  6.4   6.52  6.64
  6.76  6.88  7.    7.12  7.24  7.36  7.48  7.6   7.72  7.84  7.96  8.08
  8.2   8.32  8.44  8.56  8.68  8.8   8.92  9.04  9.16  9.28  9.4   9.52
  9.64  9.76  9.88 10.  ]


In [14]:
array3.ndim

3

In [15]:
array3.shape

(2, 3, 5)

In [16]:
array3.size

30

In [17]:
array3.dtype

dtype('int32')

In [18]:
list1=[1,2,3,4,5]

In [19]:
arraylist=np.array(list1)

In [20]:
print(arraylist)

[1 2 3 4 5]


In [23]:
array2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 22]])

In [24]:
print(array2)
print(array2*2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 11]]
[[ 2  4  6  8 10]
 [12 14 16 18 22]]


In [25]:
array1[0]

1

In [26]:
array2[1,3]

9

In [27]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [21]:
array2[1][2]

8

In [29]:
array2[1,2]*array2[0,3]

32

In [30]:
array2*array2  #(array2**2)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 121]])

In [31]:
array2[1,1]*array3[1,2,3]

238

In [32]:
print(array1)      #Factorization or proadcasting
print("______________________")
print(array2)

[1 2 3 4 5]
______________________
[[ 1  2  3  4  5]
 [ 6  7  8  9 11]]


In [33]:
print(array1*array2)

[[ 1  4  9 16 25]
 [ 6 14 24 36 55]]


In [34]:
np.sum(array3)

570

In [37]:
np.product(array3)

0

In [38]:
array1

array([1, 2, 3, 4, 5])

In [22]:
array11 = np.zeros((3,4))

In [23]:
array11[1,2]=25

In [44]:
array11

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0., 25.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [45]:
array11[2,3]=36

In [46]:
array11

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0., 25.,  0.],
       [ 0.,  0.,  0., 36.]])

In [47]:
np.sum(array11)

61.0

In [48]:
np.product(array11)

0.0

In [26]:
array22=np.ones((3,5))

In [27]:
array22

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
array22[2,1]=25

In [29]:
array22[1,2]=36

In [30]:
np.product(array22)

900.0

In [31]:
36*25

900

In [32]:
list1=['33,43,56,65,87,86']

In [33]:
array4=np.array(list1)

In [34]:
array4   

array(['33,43,56,65,87,86'], dtype='<U17')

In [35]:
list2=['king','ring', '2' ,'3','4', 'rose']

In [36]:
array5 = np.array(list2)

In [37]:
array5

array(['king', 'ring', '2', '3', '4', 'rose'], dtype='<U4')

In [38]:
value=int(array5[2])

In [39]:
type(value)

int

In [40]:
try:
    try:
        idx=int(input('enter index'))
        value=int(array5[idx])
        print(value)
    except valueError:
            print(array5[value])
except valueError:
    print("index must be a number")
    
except indexError:
    print("index out of range")
        
            

enter index4
4


In [41]:
for i in list2:
    try:
        nums.append(float(i))
    except:
        pass

nums

In [42]:
list3=['1e3','NaN','inf','3,','4']

In [43]:
for i in list2:
    try:
        nums.append(float(i))
    except:
        pass

In [44]:
array6=np.array([1,2,3,4,5,65,76,87,54,89])

In [45]:
array6.size

10

In [46]:
array6.reshape(2,5)  #reshape=change value

array([[ 1,  2,  3,  4,  5],
       [65, 76, 87, 54, 89]])

In [47]:
array7=np.ones((5,6,7))

In [48]:
array7.reshape(30,7)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
 

In [49]:
array8=np.array([1,3,4,5,67])

In [50]:
array8.size

5

In [51]:
array8.resize(2,6)    #resize=change nmuber

In [52]:
array8

array([[ 1,  3,  4,  5, 67,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [53]:
array8(50)

TypeError: 'numpy.ndarray' object is not callable

In [54]:
np.size(array2)

10

In [82]:
array2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
np.resize(array2, (4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [55]:
np.argmax(array2)  #argmax=index of max number

9

In [84]:
np.resize(array2, (50))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
#example
expenses = np.array([
    [200, 340, 345, 654, 657], #food
    [100, 768, 564, 546, 876], #travel
    [300, 376, 765, 987, 435], #shopping
])

In [87]:
print('total expenses: ',np.sum(expenses))  #these operations are very fast
print('category wise sum:',np.sum(expenses, axis =1))
print('day wise total: ', np.sum(expenses, axis =0))
print('highest expense day:', np.max(np.sum(expenses, axis=0)))

total expenses:  7913
category wise sum: [2196 2854 2863]
day wise total:  [ 600 1484 1674 2187 1968]
highest expense day: 2187


In [88]:
#example2
marks = np.array([34,65,78,54,76])

In [96]:
#where if like if else statement - takes Less time- fast
grades =np.where(marks >= 75, "A", 
        np.where(marks >= 55, "B", 
        np.where(marks >= 40,"C","Fail")))

In [97]:
print(grades)

['Fail' 'B' 'A' 'C' 'A']


In [98]:
print(marks>60) #gives boolean values

[False  True  True False  True]


In [56]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [57]:
array2.argmax()

9

In [58]:
array2.flatten()  #convert 2D array into 1D array
print(array2)
np.argmax(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 11]]


9

In [59]:
np.max(array2, axis=1)

array([ 5, 11])

In [60]:
np.sum(array2, axis=1)

array([15, 41])

In [67]:
print(array2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [72]:
arr=np.array([1,2,3,4])   #to check how much time array takes to do that operation

In [74]:
%timeit arr*1
        

835 ns ± 17.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [75]:
%timeit [i*2 for i in arr]

879 ns ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [77]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [78]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [79]:
np.square(arr)

array([ 1,  4,  9, 16])

In [80]:
np.split(arr,2)

[array([1, 2]), array([3, 4])]