In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5])

In [8]:
array2=np.array([
    [1,2,3,4,5],
    [6,7,8,9,11]]
)

In [9]:
print(array1)

[1 2 3 4 5]


In [10]:
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 11]]


In [16]:
array3=np.array([[
    [1,2,3,4,5],
    [6,7,8,9,0],
    [11,22,33,44,55]
],
                [
                    [12,14,13,16,17],
                    [21,22,23,24,33],
                    [31,32,33,34,35]
                ]])

In [20]:
print(array3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9  0]
  [11 22 33 44 55]]

 [[12 14 13 16 17]
  [21 22 23 24 33]
  [31 32 33 34 35]]]


In [23]:
array4=np.ones((2,5,4)) # 2 matrix , 5 column and 4 rows

In [24]:
print(array4)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [26]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
array6=np.linspace(1,10,76)  #1 to 10 but 76 steps

In [34]:
print(array6)

[ 1.    1.12  1.24  1.36  1.48  1.6   1.72  1.84  1.96  2.08  2.2   2.32
  2.44  2.56  2.68  2.8   2.92  3.04  3.16  3.28  3.4   3.52  3.64  3.76
  3.88  4.    4.12  4.24  4.36  4.48  4.6   4.72  4.84  4.96  5.08  5.2
  5.32  5.44  5.56  5.68  5.8   5.92  6.04  6.16  6.28  6.4   6.52  6.64
  6.76  6.88  7.    7.12  7.24  7.36  7.48  7.6   7.72  7.84  7.96  8.08
  8.2   8.32  8.44  8.56  8.68  8.8   8.92  9.04  9.16  9.28  9.4   9.52
  9.64  9.76  9.88 10.  ]


In [36]:
array3.ndim

3

In [37]:
array3.shape

(2, 3, 5)

In [38]:
array3.size

30

In [39]:
array3.dtype

dtype('int32')

In [40]:
list1=[1,2,3,4,5]

In [42]:
arraylist=np.array(list1)

In [43]:
print(arraylist)

[1 2 3 4 5]


In [44]:
array2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 22]])

In [45]:
print(array2)
print(array2*2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 11]]
[[ 2  4  6  8 10]
 [12 14 16 18 22]]


In [46]:
array1[0]

1

In [50]:
array2[1,3]

9

In [51]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [52]:
array2[1][2]

8

In [53]:
array2[1,2]*array2[0,3]

32

In [55]:
array2*array2  #(array2**2)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 121]])